### ISSUE TITLE
jdk.nashorn Error on gradle tasks

### ISSUE THREAD

**Issue by CanOfBees** [xmlresolver/sampleapp#2]
Hi there - 

I tried to build `SampleApp` from source yesterday, and I'm getting a `nashorn` related error. I think this only builds on JDK8; at least it fails on JDK11 with the following error:

```
/usr/home/bridger/src/xmlresolver-sampleapp/src/main/java/org/xmlresolver/example/SampleApp.java:14: error: package jdk.nashorn.internal.lookup is not visible
import jdk.nashorn.internal.lookup.Lookup;
                           ^
  (package jdk.nashorn.internal.lookup is declared in module jdk.scripting.nashorn, which does not export it)
```

The `dist` gradle task completes successfully when using OpenJDK1.8.

**Comment by ndw** [comment]
Oh, goodness. The reference to `jdk.nashorn.internal.lookup.Lookup` was my IDE doing completion badly. I've pushed a fix.
